# 1. FILE PATHS
paths:
  # Input data
  law_corpus: "data/alqac25_law.json"
  train_data: "data/alqac25_train.json"
  test_data: "data/alqac25_private_test_Task_1.json" 
  stopwords: "data/stopwords.txt"
  
  # Artifacts (các model/chỉ mục đã được build)
  artifacts_dir: "models/"
  bm25_model: "models/bm25_retriever.pkl"
  semantic_model: "models/semantic_retriever"
  reranker_model: "models/reranker-finetuned"

  # Output
  output_dir: "output/"
  log_file: "logs/app.log"

# 2. MODEL CONFIGURATIONS
models:
  bi_encoder: "huyydangg/DEk21_hcmute_embedding"
  cross_encoder: "vinai/phobert-base"

# 3. PIPELINE PARAMETERS
# Các siêu tham số cho quá trình retrieval và ranking
pipeline_params:
  # Số lượng ứng viên lấy ra từ mỗi retriever ban đầu
  retrieval_top_k: 100
  
  # Số lượng ứng viên tốt nhất sau khi fusion để đưa vào Re-ranker
  rerank_top_k: 50
  
  # Ngưỡng cuối cùng sẽ được định nghĩa trong submission_profiles
  # final_top_n: 5 # Không cần ở đây nữa


# 4. LOGGING CONFIGURATION
logging:
  level: "INFO"
  format: "%(asctime)s [%(levelname)s] - %(name)s - %(message)s"

# 5. SUBMISSION PROFILES
# Cho phép tạo nhiều file submission với các cài đặt khác nhau
submission_profiles:
  hybrid_best:
    method: "hybrid"
    threshold: 1
    output_file: "output/submission_1_hybrid_best.json"
    
  hybrid_recall_boost:
    method: "hybrid"
    threshold: 3
    output_file: "output/submission_2_hybrid_recall.json"
    
  rerank_backup:
    method: "rerank"
    threshold: 2
    output_file: "output/submission_3_rerank_backup.json"

